### ISSUE TITLE
Exclude glob not working

### ISSUE THREAD

**Issue by mavendonovanhubbard** [chaosaffe/split-tests#8]
I'm trying to test everything under `spec/**/*_spec.rb` while excluding tests under ``spec/selenium/*_spec.rb`. I've tried various different exclude glob patterns but none of them seem to be working. The files I want excluded are always included. 

Here is my action

```
- uses: chaosaffe/split-tests@4f1ca766cb93923ca216e02f1aefed20944e313f
  id: split-tests
  name: Split tests
  with:
    glob: spec/**/*_spec.rb
    split-total: ${{ env.rspec-runners }}
    split-index: ${{ matrix.rspec_index }}
    exclude-glob: spec/selenium/**/*_spec.rb
    line-count: true
```

Some of the other patterns I've tried.

- "\*selenium\*"
- spec/selenium/services_spec.rb
